import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  favicon:'https://res.cloudinary.com/duqilis2i/image/upload/v1695833433/Portfolio/Logo-blanco_todfus.png',
  title: 'Emiliano Perea Developer',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     <head>
        <link rel="icon" href={metadata.favicon} />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
